/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3pqeXUvR2l0Qm9vay9MaWJyYXJ5L0ltcG9ydC9sZWFybi1hbmd1bGFyL2NvZGUtZXhhbXBsZXMvMDAxLTAwMy9sZWFybi1hbmd1bGFyLXN0ZXAtMDAyL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvemp5dS9HaXRCb29rL0xpYnJhcnkvSW1wb3J0L2xlYXJuLWFuZ3VsYXIvY29kZS1leGFtcGxlcy8wMDEtMDAzL2xlYXJuLWFuZ3VsYXItc3RlcC0wMDIvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
