/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './app.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './app.component';
const styles_AppComponent:any[] = [import0.styles];
export const RenderType_AppComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_AppComponent,
  data: {}
}
);
export function View_AppComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      '\n  ',
      '\n'
    ]
    )),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(ck,v) => {
    var co:import2.AppComponent = v.component;
    const currVal_0:any = co.title;
    ck(v,1,0,currVal_0);
  });
}
function View_AppComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
    import1.ɵdid(49152,(null as any),0,import2.AppComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AppComponentNgFactory:import1.ComponentFactory<import2.AppComponent> = import1.ɵccf('app-root',import2.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3pqeXUvR2l0Qm9vay9MaWJyYXJ5L0ltcG9ydC9sZWFybi1hbmd1bGFyL2NvZGUtZXhhbXBsZXMvMDAxLTAwMy9sZWFybi1hbmd1bGFyLXN0ZXAtMDAzL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy96anl1L0dpdEJvb2svTGlicmFyeS9JbXBvcnQvbGVhcm4tYW5ndWxhci9jb2RlLWV4YW1wbGVzLzAwMS0wMDMvbGVhcm4tYW5ndWxhci1zdGVwLTAwMy9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy96anl1L0dpdEJvb2svTGlicmFyeS9JbXBvcnQvbGVhcm4tYW5ndWxhci9jb2RlLWV4YW1wbGVzLzAwMS0wMDMvbGVhcm4tYW5ndWxhci1zdGVwLTAwMy9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3pqeXUvR2l0Qm9vay9MaWJyYXJ5L0ltcG9ydC9sZWFybi1hbmd1bGFyL2NvZGUtZXhhbXBsZXMvMDAxLTAwMy9sZWFybi1hbmd1bGFyLXN0ZXAtMDAzL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+XG4gIHt7dGl0bGV9fVxuPC9oMT5cbiIsIjxhcHAtcm9vdD48L2FwcC1yb290PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFBSTtNQUFBO01BQUE7SUFBQTtJQUFBO0lBRUM7Ozs7SUFGRDtJQUFBOzs7OztJQ0FKO2dCQUFBOzs7OyJ9
